name: update-tedge-reference-documents

on:
  schedule:
  - cron: "0 0 1 * *"
     
jobs:
    install-and-use-amd64:
      runs-on: Ubuntu-20.04
      
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - run: |
           git config --global user.email "pradeepkiruvale@gmail.com"
           git config --global user.name "pradeepkiruvale"
           
        - name: enable toolchain via github action
          # https://github.com/actions-rs/toolchain
          uses: actions-rs/toolchain@v1
          with:
            toolchain: 1.58
            override: true

        - name: Enable cache
          # https://github.com/marketplace/actions/rust-cache
          uses: Swatinem/rust-cache@v1
        
        - name: Build tedge
          uses: actions-rs/cargo@v1
          # https://github.com/marketplace/actions/rust-cargo
          with:
            command: build
            args: --release -p tedge

        # - name: Download artifact
        # uses: dawidd6/action-download-artifact@v2
        # # https://github.com/marketplace/actions/download-workflow-artifact
        # with:
        #   github_token: ${{secrets.GITHUB_TOKEN}}
        #   workflow: build-workflow.yml
        #   workflow_conclusion: success
        #   branch: main
        #   name: debian-packages-amd64
        #   path: debian-package_unpack
          
        # - name: install packages
        #   run: sudo dpkg -i ./debian-package_unpack/*.deb
        - name: run the update script
          run: ./docs/gen-ref-docs.sh
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v3
          with:
            commit-message: Create tedge docs
            delete-branch: true
            title: Create tedge docs
            body: Create tedge docs
            reviewers: Pradeepkiruvale  
