name: update-tedge-reference-documents

on:
  workflow_dispatch:
    branches: [main]
    
env:
  CARGO_TERM_COLOR: always
  
jobs:
    install-and-use-amd64:
      runs-on: Ubuntu-20.04
      
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - run: |
           git config --global user.email "pradeepkiruvale@gmail.com"
           git config --global user.name "pradeepkiruvale"
            steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: enable toolchain via github action
          # https://github.com/actions-rs/toolchain
          uses: actions-rs/toolchain@v1
          with:
            toolchain: 1.58
            override: true

        - name: Enable cache
          # https://github.com/marketplace/actions/rust-cache
          uses: Swatinem/rust-cache@v1

        - name: Install cargo-deb
          uses: actions-rs/cargo@v1
          # https://github.com/marketplace/actions/rust-cargo
          with:
            command: install
            args: cargo-deb --version 1.34.2

        - name: Build tedge debian package
          uses: actions-rs/cargo@v1
          # https://github.com/marketplace/actions/rust-cargo
          with:
            command: deb
            args: -p tedge

        # - name: Download artifact
        # uses: dawidd6/action-download-artifact@v2
        # # https://github.com/marketplace/actions/download-workflow-artifact
        # with:
        #   github_token: ${{secrets.GITHUB_TOKEN}}
        #   workflow: build-workflow.yml
        #   workflow_conclusion: success
        #   branch: main
        #   name: debian-packages-amd64
        #   path: debian-package_unpack
          
        # - name: install packages
        #   run: sudo dpkg -i ./debian-package_unpack/*.deb
        - name: run the update script
          run: ./doc/gen-ref-docs.sh
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v3
          with:
            commit-message: Create tedge docs
            delete-branch: true
            title: Create tedge docs
            body: Create tedge docs
            reviewers: Pradeep  
